# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 04:16


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0003_auto_20180206_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='field')),
                ('field_value', models.CharField(max_length=255, verbose_name='field value')),
                ('action_type', models.CharField(choices=[('email', 'Email to'), ('redirect', 'Redirect to')], max_length=20, verbose_name='action')),
                ('action_value', models.CharField(max_length=255, verbose_name='to name')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionals', to='email_notifications.EmailNotificationFormPlugin')),
            ],
            options={
                'verbose_name': 'conditional',
                'verbose_name_plural': 'conditionals',
            },
        ),
    ]
