# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_forms', '0011_auto_20180110_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatedContentContainerPlugin',
            fields=[
                ('attributes', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Attributes')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_forms_gatedcontentcontainerplugin', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('default', 'Email and save'), ('email_only', 'Email only'), ('none', 'None')], default='default', max_length=15, verbose_name='Action'),
        ),
    ]
