# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0013_mandrillemailfieldplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='download_url',
            field=models.URLField(blank=True, null=True, verbose_name='download URL'),
        ),
        migrations.AddField(
            model_name='formplugin',
            name='form_type',
            field=models.CharField(blank=True, choices=[('event', 'Event'), ('download', 'Download'), ('contact', 'Contact'), ('', 'Other')], max_length=255, null=True, verbose_name='form type'),
        ),
    ]
