# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 08:51


from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('aldryn_forms', '0014_auto_20191218_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='download_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='download file'),
        ),
        migrations.AddField(
            model_name='formplugin',
            name='form_id',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='action_backend',
            field=models.CharField(choices=[('api_only', 'API Only'), ('email_api', 'Email and API'), ('default', 'Email and save'), ('email_only', 'Email only'), ('none', 'None')], default='default', max_length=15, verbose_name='Action'),
        ),
    ]
