# Generated by Django 2.2.15 on 2020-09-24 09:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0015_auto_20200204_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='People who will get the form content via e-mail.', limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL, verbose_name='Recipients'),
        ),
    ]
